# This is a basic workflow to help you get started with Actions

name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
      - name: "Build Android project"
        uses: vgaidarji/android-github-actions-build@v1.0.1
      - name: Setup Android problem matchers
        uses: jonasb/android-problem-matchers-action@v1
